// Code generated by goctl. DO NOT EDIT!
// Source: coupon.proto

package coupon

import (
	"context"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	Coupon interface {
		FindCouponById(ctx context.Context, in *FindCouponRequest, opts ...grpc.CallOption) (*FindCouponResponse, error)
		DeductStockById(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error)
	}

	defaultCoupon struct {
		cli zrpc.Client
	}
)

func NewCoupon(cli zrpc.Client) Coupon {
	return &defaultCoupon{
		cli: cli,
	}
}

func (m *defaultCoupon) FindCouponById(ctx context.Context, in *FindCouponRequest, opts ...grpc.CallOption) (*FindCouponResponse, error) {
	client := NewCouponClient(m.cli.Conn())
	return client.FindCouponById(ctx, in, opts...)
}

func (m *defaultCoupon) DeductStockById(ctx context.Context, in *DeductStockRequest, opts ...grpc.CallOption) (*DeductStockResponse, error) {
	client := NewCouponClient(m.cli.Conn())
	return client.DeductStockById(ctx, in, opts...)
}
