// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package product

import (
	"context"

	"product-search-service/rpc/types/product"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	IdReq            = product.IdReq
	ProductInfoReply = product.ProductInfoReply

	Product interface {
		GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ProductInfoReply, error)
	}

	defaultProduct struct {
		cli zrpc.Client
	}
)

func NewProduct(cli zrpc.Client) Product {
	return &defaultProduct{
		cli: cli,
	}
}

func (m *defaultProduct) GetProduct(ctx context.Context, in *IdReq, opts ...grpc.CallOption) (*ProductInfoReply, error) {
	client := product.NewProductClient(m.cli.Conn())
	return client.GetProduct(ctx, in, opts...)
}
