// Code generated by goctl. DO NOT EDIT.
package types

type LoginRequest struct {
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
}

type LoginResponse struct {
	Id          int64  `json:"id"`
	AuthorityId int64  `json:"authorityId"`
	AccessToken string `json:"accessToken"`
}
