// Code generated by goctl. DO NOT EDIT.
package types

type RegisterRequest struct {
	Name        string `json:"name"`
	PhoneNumber string `json:"phoneNumber"`
	Password    string `json:"password"`
	Age         int64  `json:"age"`
	Gender      int64  `json:"gender"`
	Avatar      string `json:"avatar"`
}

type RegisterResponse struct {
	Id int64 `json:"id"`
}
