Name: product.rpc
ListenOn: 127.0.0.1:7010
Etcd:
  Hosts:
  - 127.0.0.1:2379
  Key: product.rpc
Mysql:
  DataSource: root:45568769zby@tcp(127.0.0.1:3306)/seckill?charset=utf8mb4
CacheRedis:
  - Host: 127.0.0.1:6379
    Type: node
