// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"seckill/service/user_login/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/api/v1/user/login",
				Handler: loginHandler(serverCtx),
			},
		},
	)
}
