// Code generated by goctl. DO NOT EDIT.
package types

type SearchReq struct {
	Id int64 `json:"id"`
}

type SearchReply struct {
	Name        string  `json:"name"`
	Price       float64 `json:"price"`
	Stock       int64   `json:"stock"`
	TypeId      int64   `json:"typeId"`
	SalesVolume int64   `json:"salesVolume"`
	SpuId       int64   `json:"spuId"`
}
