// Code generated by goctl. DO NOT EDIT.
package types

type NormalGetCouponRequest struct {
	UserId   int64 `json:"userId"`
	CouponId int64 `json:"couponId"`
}

type NormalGetCouponResponse struct {
	Uuid   string `json:"uuid"`
	Status int64  `json:"status"`
}

type GetUserCouponRequest struct {
	Uuid string `path:"uuid"`
}

type GetUserCouponResponse struct {
	UserId   int64 `json:"userId"`
	CouponId int64 `json:"couponId"`
	Status   int64 `json:"status"`
}
