// Code generated by goctl. DO NOT EDIT!
// Source: product.proto

package server

import (
	"context"

	"product-search-service/rpc/internal/logic"
	"product-search-service/rpc/internal/svc"
	"product-search-service/rpc/types/product"
)

type ProductServer struct {
	svcCtx *svc.ServiceContext
	product.UnimplementedProductServer
}

func NewProductServer(svcCtx *svc.ServiceContext) *ProductServer {
	return &ProductServer{
		svcCtx: svcCtx,
	}
}

func (s *ProductServer) GetProduct(ctx context.Context, in *product.IdReq) (*product.ProductInfoReply, error) {
	l := logic.NewGetProductLogic(ctx, s.svcCtx)
	return l.GetProduct(in)
}
