// Code generated by goctl. DO NOT EDIT!
// Source: coupon.proto

package server

import (
	"context"

	"seckill/service/coupon/rpc/coupon"
	"seckill/service/coupon/rpc/internal/logic"
	"seckill/service/coupon/rpc/internal/svc"
)

type CouponServer struct {
	svcCtx *svc.ServiceContext
	coupon.UnimplementedCouponServer
}

func NewCouponServer(svcCtx *svc.ServiceContext) *CouponServer {
	return &CouponServer{
		svcCtx: svcCtx,
	}
}

func (s *CouponServer) FindCouponById(ctx context.Context, in *coupon.FindCouponRequest) (*coupon.FindCouponResponse, error) {
	l := logic.NewFindCouponByIdLogic(ctx, s.svcCtx)
	return l.FindCouponById(in)
}

func (s *CouponServer) DeductStockById(ctx context.Context, in *coupon.DeductStockRequest) (*coupon.DeductStockResponse, error) {
	l := logic.NewDeductStockByIdLogic(ctx, s.svcCtx)
	return l.DeductStockById(in)
}
