// Code generated by goctl. DO NOT EDIT.
package types

type AddCouponRequest struct {
	Name           string `json:"name"`
	WithAmount     int    `json:"withAmount"`
	UsedAmount     int    `json:"usedAmount"`
	Stock          int    `json:"stock"`
	StartTime      int64  `json:"startTime"`
	EndTime        int64  `json:"endTime"`
	Status         int    `json:"status"`
	ValidStartTime int64  `json:"validStartTime"`
	ValidEndTime   int64  `json:"validEndTime"`
}

type AddCouponResponse struct {
	Id int64 `json:"id"`
}
