// Code generated by goctl. DO NOT EDIT.
package types

type LoginReq struct {
	Email    string `json:"email"`
	Password string `json:"password"`
}

type LoginReply struct {
	Id           int64  `json:"id"`
	Name         string `json:"name"`
	Gender       int64  `json:"gender"`
	Email        string `json:"email"`
	PhoneNumber  int64  `json:"phoneNumber"`
	Age          int    `json:"age"`
	Avatar       string `json:"avatar"`
	AuthorityId  int64  `json:"authorityId"`
	AccessToken  string `json:"accessToken"`
	AccessExpire int64  `json:"accessExpire"`
	RefreshAfter int64  `json:"refreshAfter"`
}
